//! Remediation script generation for AutomateSTIG.
//!
//! Generates platform-specific remediation scripts (Ansible, PowerShell, Bash)
//! from STIG findings. Scripts are deterministic and auditable.

use serde::{Deserialize, Serialize};

/// A remediation script that can be applied to fix a finding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemediationScript {
    /// Script identifier.
    pub id: String,

    /// Target Vuln ID(s) this script addresses.
    pub vuln_ids: Vec<String>,

    /// Human-readable description of what the script does.
    pub description: String,

    /// Script format/language.
    pub format: ScriptFormat,

    /// The actual script content.
    pub content: String,

    /// Whether this script requires elevated privileges.
    pub requires_admin: bool,

    /// Whether this script requires a reboot after application.
    pub requires_reboot: bool,

    /// Risk level of applying this remediation.
    pub risk: RemediationRisk,

    /// Whether this script is reversible.
    pub reversible: bool,

    /// Rollback script (if reversible).
    pub rollback_content: Option<String>,
}

/// Remediation script format.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ScriptFormat {
    #[serde(rename = "powershell")]
    PowerShell,
    #[serde(rename = "bash")]
    Bash,
    #[serde(rename = "ansible")]
    Ansible,
    #[serde(rename = "cmd")]
    Cmd,
}

impl std::fmt::Display for ScriptFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::PowerShell => write!(f, "PowerShell"),
            Self::Bash => write!(f, "Bash"),
            Self::Ansible => write!(f, "Ansible"),
            Self::Cmd => write!(f, "CMD"),
        }
    }
}

/// Risk level of applying a remediation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RemediationRisk {
    /// Safe to apply — low impact, easily reversible.
    #[serde(rename = "low")]
    Low,
    /// Moderate impact — may affect service availability.
    #[serde(rename = "medium")]
    Medium,
    /// High impact — could cause outage or require significant testing.
    #[serde(rename = "high")]
    High,
}

/// A remediation plan — a collection of scripts to fix multiple findings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemediationPlan {
    /// Plan name.
    pub name: String,

    /// Target hostname.
    pub target_host: String,

    /// Scripts in execution order.
    pub scripts: Vec<RemediationScript>,

    /// Whether the plan requires a reboot at the end.
    pub requires_reboot: bool,

    /// Overall risk assessment.
    pub overall_risk: RemediationRisk,
}

impl RemediationPlan {
    /// Create a new empty remediation plan.
    pub fn new(name: &str, target_host: &str) -> Self {
        Self {
            name: name.to_string(),
            target_host: target_host.to_string(),
            scripts: Vec::new(),
            requires_reboot: false,
            overall_risk: RemediationRisk::Low,
        }
    }

    /// Add a script to the plan.
    pub fn add_script(&mut self, script: RemediationScript) {
        if script.requires_reboot {
            self.requires_reboot = true;
        }
        if script.risk as u8 > self.overall_risk as u8 {
            self.overall_risk = script.risk;
        }
        self.scripts.push(script);
    }

    /// Get the total number of findings addressed.
    pub fn findings_addressed(&self) -> usize {
        self.scripts.iter().map(|s| s.vuln_ids.len()).sum()
    }
}

/// Generate a registry fix script for Windows.
pub fn generate_registry_fix(
    vuln_id: &str,
    description: &str,
    reg_path: &str,
    value_name: &str,
    value_type: &str,
    value_data: &str,
) -> RemediationScript {
    let ps_content = format!(
        r#"# AutomateSTIG Remediation - {vuln_id}
# {description}
# Generated by AutomateSTIG - DO NOT EDIT MANUALLY

$ErrorActionPreference = 'Stop'

$regPath = '{reg_path}'
$valueName = '{value_name}'
$valueType = '{value_type}'
$valueData = '{value_data}'

# Ensure the registry path exists.
if (-not (Test-Path $regPath)) {{
    New-Item -Path $regPath -Force | Out-Null
    Write-Host "Created registry path: $regPath"
}}

# Set the value.
Set-ItemProperty -Path $regPath -Name $valueName -Value $valueData -Type $valueType
Write-Host "Set $regPath\$valueName = $valueData ($valueType)"
Write-Host "Remediation for {vuln_id} applied successfully."
"#
    );

    RemediationScript {
        id: format!("fix-{}", vuln_id.to_lowercase()),
        vuln_ids: vec![vuln_id.to_string()],
        description: description.to_string(),
        format: ScriptFormat::PowerShell,
        content: ps_content,
        requires_admin: true,
        requires_reboot: false,
        risk: RemediationRisk::Low,
        reversible: true,
        rollback_content: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_remediation_plan() {
        let mut plan = RemediationPlan::new("Fix TLS", "webserver01");

        plan.add_script(RemediationScript {
            id: "fix-v-254239".to_string(),
            vuln_ids: vec!["V-254239".to_string()],
            description: "Enable TLS 1.2".to_string(),
            format: ScriptFormat::PowerShell,
            content: "# Enable TLS 1.2".to_string(),
            requires_admin: true,
            requires_reboot: true,
            risk: RemediationRisk::Medium,
            reversible: true,
            rollback_content: None,
        });

        assert_eq!(plan.findings_addressed(), 1);
        assert!(plan.requires_reboot);
        assert_eq!(plan.overall_risk, RemediationRisk::Medium);
    }

    #[test]
    fn test_generate_registry_fix() {
        let script = generate_registry_fix(
            "V-254239",
            "Enable TLS 1.2",
            "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Client",
            "Enabled",
            "DWord",
            "1",
        );

        assert_eq!(script.vuln_ids, vec!["V-254239"]);
        assert_eq!(script.format, ScriptFormat::PowerShell);
        assert!(script.content.contains("TLS 1.2"));
        assert!(script.requires_admin);
    }
}
